### ISSUE TITLE
License

### ISSUE THREAD

**Issue by notpushkin** [Its-Vichy/cloudflare_bypass#1]
Hey, first of all thanks for your wonderful project!

I've noticed this repo lacks a LICENSE file, which is the usual way of specifying the project's license. This means the project is [not licensed / non-open source](https://choosealicense.com/no-permission/), and people can't use it legally. I understand that this is a simple demo, but it could be extremely useful e. g. for archival projects. Could you [pick a license](https://choosealicense.com/) and add it to the repo? Let me know if you need any help with that!

**Comment by Its-Vichy** [comment]
Hi, checkout https://github.com/Its-Vichy/cloudflare_bypass/commit/eab05c0d51e4c0b53a2e1b3ed19651d10f861036 👍
