### ISSUE TITLE
index out of range [1] with length 1

### ISSUE THREAD

**Issue by CryonicsX** [Its-Vichy/cloudflare_bypass#3]
[FETCH] https://discord.com
[FETCH] https://discord.com/cdn-cgi/challenge-platform/h/b/scripts/alpha/invisible.js?ts=1667642182
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
cfBypass/components/cloudflare.(*Session).GetCfParams(0x0?)
        C:/Users/90541/Desktop/cloudflare_bypass/src/components/cloudflare/cloudflare.go:78 +0x7d2
main.main()
        C:/Users/90541/Desktop/cloudflare_bypass/src/main.go:10 +0x6d
exit status 2

**Comment by Its-Vichy** [comment]
Same as https://github.com/Its-Vichy/cloudflare_bypass/issues/2
